# Generated by Django 3.1 on 2020-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200818_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
