# Generated by Django 3.1 on 2020-08-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_cart'),
        ('carts', '0004_auto_20200826_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payment'),
        ),
    ]
